# Generated by Django 3.2.8 on 2021-10-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('codigoPostal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('sitio_web', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.domicilio')),
            ],
        ),
    ]
