# Generated by Django 3.2.8 on 2021-10-17 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre_prod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cod_prod', models.CharField(max_length=5, unique=True)),
                ('categ_prod', models.CharField(max_length=20)),
                ('precio_uni', models.IntegerField()),
                ('descrip_prod', models.CharField(max_length=100)),
                ('prod_act', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='descripcion',
            new_name='descrip_emp',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='domicilio',
            new_name='domicilio_emp',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefono',
            new_name='tlfn_emp',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_emp',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre_cont', models.CharField(max_length=50)),
                ('apellido_cont', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo_contacto', models.CharField(max_length=50)),
                ('email_cont', models.EmailField(max_length=254)),
                ('movil_cont', models.CharField(max_length=8)),
                ('tlfn_cont', models.CharField(max_length=8)),
                ('tlfn_casa', models.CharField(max_length=8)),
                ('email_opt_out', models.CharField(max_length=10)),
                ('descrip_cont', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.empresa')),
            ],
        ),
    ]
