# Generated by Django 3.2.8 on 2021-10-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0002_auto_20211017_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=50)),
                ('us_lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('us_password', models.CharField(max_length=15)),
                ('us_email', models.EmailField(max_length=254)),
                ('us_phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('task_duedate', models.DateField()),
                ('repeat', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('priority', models.BooleanField(default=False)),
                ('relatedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('repeat', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('relatedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.contacto')),
            ],
        ),
    ]
