# Generated by Django 3.2.8 on 2021-11-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0003_event_task_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trato',
            fields=[
                ('trato_nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[[0, 'Clasificación'], [1, 'Dimensionamiento'], [2, 'Cotización de propuesta/precio'], [3, 'Negociación/revisión'], [4, 'Facturado'], [5, 'Pagado'], [6, 'Cerrado ganado'], [7, 'Cerrado perdido']])),
                ('cant', models.FloatField()),
                ('fechacierre', models.DateField()),
                ('desc', models.CharField(max_length=100)),
                ('cont_nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.contacto')),
                ('emp_nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.empresa')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.producto')),
            ],
        ),
    ]
