# Generated by Django 3.2.8 on 2021-11-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0004_trato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellido_cont',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descrip_cont',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='movil_cont',
            field=models.CharField(max_length=8, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_cont',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='titulo_contacto',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tlfn_casa',
            field=models.CharField(max_length=8, verbose_name='Teléfono de casa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tlfn_cont',
            field=models.CharField(max_length=8, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descrip_emp',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_emp',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tlfn_emp',
            field=models.CharField(max_length=8, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='event',
            name='relatedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.contacto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='relatedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionDatos.contacto'),
        ),
    ]
