# Generated by Django 3.2.8 on 2021-11-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0005_auto_20211105_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Evento',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Tarea',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
