# Generated by Django 3.2.8 on 2021-11-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0006_auto_20211105_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trato',
            old_name='cont_nombre',
            new_name='contacto_nombre',
        ),
        migrations.RenameField(
            model_name='trato',
            old_name='desc',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='trato',
            old_name='emp_nombre',
            new_name='empresa_nombre',
        ),
        migrations.RenameField(
            model_name='trato',
            old_name='prod',
            new_name='producto',
        ),
    ]
